#### 1. Bag of Words technique - (BOW)
To represent the text in Count format

In [6]:
import pandas as pd

# Sample text data
data = [
    "The cat sat on the mat.",
    "The dog chased the cat.",
    "The dog sat on the mat.",
    "The cat played with the dog.",
    "The bird flew over the cat and dog."
]



columns = ['text']

df = pd.DataFrame(data, columns=columns)
df

text
0              The cat sat on the mat.
1              The dog chased the cat.
2              The dog sat on the mat.
3         The cat played with the dog.
4  The bird flew over the cat and dog.

In [8]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

bow = cv.fit_transform(df['text'])

In [10]:
bow.toarray()

array([[0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 2, 0],
       [0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 2, 0],
       [0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 2, 0],
       [0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 2, 1],
       [1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 2, 0]])

In [15]:
print(cv.vocabulary_)

{'the': 11, 'cat': 2, 'sat': 10, 'on': 7, 'mat': 6, 'dog': 4, 'chased': 3, 'played': 9, 'with': 12, 'bird': 1, 'flew': 5, 'over': 8, 'and': 0}


#### 2. NGrams

##### 2. BiGrams

In [31]:
cv = CountVectorizer(ngram_range=(2,2))
bow2 = cv.fit_transform(df['text'])
print(cv.vocabulary_)

{'the cat': 14, 'cat sat': 4, 'sat on': 12, 'on the': 9, 'the mat': 16, 'the dog': 15, 'dog chased': 6, 'chased the': 5, 'dog sat': 7, 'cat played': 3, 'played with': 11, 'with the': 17, 'the bird': 13, 'bird flew': 1, 'flew over': 8, 'over the': 10, 'cat and': 2, 'and dog': 0}


In [32]:
bow2.toarray()

array([[0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1],
       [1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0]])

##### 2.b TriGrams

In [33]:
cv = CountVectorizer(ngram_range=(3,3))
bow3 = cv.fit_transform(df['text'])
print(cv.vocabulary_)

{'the cat sat': 15, 'cat sat on': 3, 'sat on the': 11, 'on the mat': 8, 'the dog chased': 16, 'dog chased the': 5, 'chased the cat': 4, 'the dog sat': 17, 'dog sat on': 6, 'the cat played': 14, 'cat played with': 2, 'played with the': 10, 'with the dog': 18, 'the bird flew': 12, 'bird flew over': 0, 'flew over the': 7, 'over the cat': 9, 'the cat and': 13, 'cat and dog': 1}


In [36]:
bow3.toarray()

array([[0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1],
       [1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0]])

#### 3. TF-IDF (Term Frequency - Inverse Document Frequency)

In [37]:
# TFIDF = TF * IDF
# TF = How many times a word in coming in the current document)
# IDF = log 
    # (
    # Total number of documents
    #           / 
    # Number of time Word is coming in all the documents 
    # )    

In [38]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()
arr = tfidf.fit_transform(df['text']).toarray()
arr

array([[0.        , 0.        , 0.31600987, 0.        , 0.        ,
        0.        , 0.4525429 , 0.4525429 , 0.        , 0.        ,
        0.4525429 , 0.53455825, 0.        ],
       [0.        , 0.        , 0.35328705, 0.62708198, 0.35328705,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.59761585, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.31600987,
        0.        , 0.4525429 , 0.4525429 , 0.        , 0.        ,
        0.4525429 , 0.53455825, 0.        ],
       [0.        , 0.        , 0.29930642, 0.        , 0.29930642,
        0.        , 0.        , 0.        , 0.        , 0.53126675,
        0.        , 0.5063029 , 0.53126675],
       [0.42474318, 0.42474318, 0.2392929 , 0.        , 0.2392929 ,
        0.42474318, 0.        , 0.        , 0.42474318, 0.        ,
        0.        , 0.4047848 , 0.        ]])

In [41]:
print(tfidf.vocabulary_, tfidf.idf_, sep="\n")

{'the': 11, 'cat': 2, 'sat': 10, 'on': 7, 'mat': 6, 'dog': 4, 'chased': 3, 'played': 9, 'with': 12, 'bird': 1, 'flew': 5, 'over': 8, 'and': 0}
[2.09861229 2.09861229 1.18232156 2.09861229 1.18232156 2.09861229
 1.69314718 1.69314718 2.09861229 2.09861229 1.69314718 1.
 2.09861229]


#### 4. Word2Vec Technique

In [46]:
import numpy as np 
import pandas as pd
import gensim
import os

In [47]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /home/de-ninja/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [53]:
pwd

'/home/de-ninja/Documents/Courses/Gen-AI-freecodecamp'

In [64]:
story = []
for file in os.listdir('GOT books'):
    if file == ".ipynb_checkpoints":
        pass
    else:
        f = open(os.path.join('GOT books', file), encoding='unicode_escape')
        corpus = f.read()
        # print(f)
        tokens = sent_tokenize(corpus)
        for token in tokens:
            story.append(simple_preprocess(token))

In [67]:
model = gensim.models.Word2Vec(
    window = 10,
    min_count = 2 
)
model.build_vocab(story)
model.train(story, total_examples=model.corpus_count, epochs=model.epochs)

(6569866, 8628190)

In [84]:
model.wv.most_similar('jaime')

[('tyrion', 0.8551657795906067),
 ('cersei', 0.7381189465522766),
 ('davos', 0.6893479228019714),
 ('brienne', 0.6819226741790771),
 ('ned', 0.6742334961891174),
 ('littlefinger', 0.6327482461929321),
 ('theon', 0.6226832866668701),
 ('bronn', 0.6183401346206665),
 ('hound', 0.6157232522964478),
 ('catelyn', 0.6154235005378723)]

In [93]:
model.wv.similarity('arya', 'sansa')

0.85418594

##### PCA

In [94]:
from sklearn.decomposition import PCA
pca = PCA(n_components=3)
X = pca.fit_transform(model.wv.get_normed_vectors())

In [95]:
X

array([[ 0.13593999, -0.5969083 ,  0.03683241],
       [ 0.17027196, -0.33013898, -0.05908604],
       [-0.29053146, -0.5784489 , -0.20001513],
       ...,
       [-0.4151773 , -0.08914551, -0.18182142],
       [-0.02611536,  0.09978819,  0.05820008],
       [-0.10088348,  0.22486311,  0.16903715]], dtype=float32)

In [106]:
X.shape

(17453, 3)

In [114]:
X[0:4][1]

array([ 0.17027196, -0.33013898, -0.05908604], dtype=float32)

In [122]:
from pyspark.sql import SparkSession
from pyspark.sql.types import *
from pyspark.sql.functions import split, split_part

In [118]:
spark = SparkSession.builder.appName('test').getOrCreate()

24/11/18 21:50:48 WARN Utils: Your hostname, codebase resolves to a loopback address: 127.0.1.1; using 10.255.255.254 instead (on interface lo)
24/11/18 21:50:48 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
24/11/18 21:50:49 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
24/11/18 21:51:08 WARN GarbageCollectionMetrics: To enable non-built-in garbage collector(s) List(G1 Concurrent GC), users should configure it(them) to spark.eventLog.gcMetrics.youngGenerationGarbageCollectors or spark.eventLog.gcMetrics.oldGenerationGarbageCollectors


In [119]:
from pyspark.sql import SparkSession
from pyspark.sql.types import StructType, StructField, StringType, IntegerType

# Initialize Spark session
spark = SparkSession.builder.appName("CreateTables").getOrCreate()

# Data for the first table
data1 = [
    ("DIV-NY_12345", 500),
    ("DIV-LA_67890", 300),
    ("DIV-SF_11223", 800),
    ("DIV-NY_54321", 200),
    ("DIV-LA_98765", 100),
]

schema1 = StructType([
    StructField("Division_ID", StringType(), True),
    StructField("Amount", IntegerType(), True),
])

df1 = spark.createDataFrame(data1, schema=schema1)

# Data for the second table
data2 = [
    ("NY", "New York"),
    ("LA", "Los Angeles"),
    ("SF", "San Francisco"),
]

schema2 = StructType([
    StructField("City_Abbreviation", StringType(), True),
    StructField("Full_Location_Name", StringType(), True),
])

df2 = spark.createDataFrame(data2, schema=schema2)

# Show the data
print("Table 1: Division ID and Amount")
df1.show()

print("Table 2: City Abbreviation and Full Location Name")
df2.show()


24/11/18 21:52:43 WARN SparkSession: Using an existing Spark session; only runtime SQL configurations will take effect.


Table 1: Division ID and Amount


+------------+------+
| Division_ID|Amount|
+------------+------+
|DIV-NY_12345|   500|
|DIV-LA_67890|   300|
|DIV-SF_11223|   800|
|DIV-NY_54321|   200|
|DIV-LA_98765|   100|
+------------+------+

Table 2: City Abbreviation and Full Location Name
+-----------------+------------------+
|City_Abbreviation|Full_Location_Name|
+-----------------+------------------+
|               NY|          New York|
|               LA|       Los Angeles|
|               SF|     San Francisco|
+-----------------+------------------+



In [139]:
df1.withColumn('key', split(split("Division_ID",'-')[1], "_")[0]).show()
df1.join(df2, split(split(df1["Division_ID"],'-')[1], "_")[0] == df2['City_Abbreviation'], 'inner').show()

+------------+------+---+
| Division_ID|Amount|key|
+------------+------+---+
|DIV-NY_12345|   500| NY|
|DIV-LA_67890|   300| LA|
|DIV-SF_11223|   800| SF|
|DIV-NY_54321|   200| NY|
|DIV-LA_98765|   100| LA|
+------------+------+---+



[Stage 40:==============================================>         (10 + 2) / 12]

+------------+------+-----------------+------------------+
| Division_ID|Amount|City_Abbreviation|Full_Location_Name|
+------------+------+-----------------+------------------+
|DIV-LA_67890|   300|               LA|       Los Angeles|
|DIV-LA_98765|   100|               LA|       Los Angeles|
|DIV-NY_12345|   500|               NY|          New York|
|DIV-NY_54321|   200|               NY|          New York|
|DIV-SF_11223|   800|               SF|     San Francisco|
+------------+------+-----------------+------------------+



In [128]:
df1.createOrReplaceTempView('df1')
df2.createOrReplaceTempView('df2')

In [133]:
spark.sql(
    """
    SELECT a.*, b.full_location_name FROM df1 a 
    LEFT JOIN df2 b 
    ON substr(a.Division_ID, 5, LENGTH(a.Division_ID) - 10) = b.City_Abbreviation
    """
).show(10, False)

[Stage 28:==============>                                          (3 + 9) / 12]

+------------+------+------------------+
|Division_ID |Amount|full_location_name|
+------------+------+------------------+
|DIV-NY_12345|500   |New York          |
|DIV-LA_67890|300   |Los Angeles       |
|DIV-SF_11223|800   |San Francisco     |
|DIV-NY_54321|200   |New York          |
|DIV-LA_98765|100   |Los Angeles       |
+------------+------+------------------+

